### ISSUE TITLE
src.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by DavidFH** [majorleaguesoccer/respectify#16]
Getting this error when trying to sanitise a path. 

{"code":"InternalError","message":"src.hasOwnProperty is not a function"}

Route is as follows:

```
server.get({
      path: '/api/test',
      params: {
        name: {
          required: true,
          dataTypes: ['string']
        }
      }
    }, (req, res) => {
      console.log(req);
      res.send('testing');
    })
```

Restify is setup as follows:

```
let server = restify.createServer({
      name: 'projectSite'
    });

    let respect = new Respectify(server);

    server
      .use(restify.CORS({
        origins: ['*'],
        credentials: true,
        headers: ['authorization', 'content-type', 'accept', 'origin', 'sid'],
        methods: ['GET', 'PUT', 'POST', 'HEAD', 'DELETE']
      }))
      .use(restify.bodyParser())
      .use(restify.queryParser())
      .use(restify.authorizationParser())
      .use(respect.middleware());
```

**Comment by sorensen** [comment]
@DavidFH Thanks for reporting this, I will try to reproduce this locally.

What versions of `node`, `restify`, and `respectify` are you using?

**Comment by DavidFH** [comment]
@sorensen Thank you for the reply. The versions are as follows:

node 5.9.0
restify 4.0.4
respectify 2.3.1

How would one go about getting the stack trace for this?

**Comment by sorensen** [comment]
@DavidFH I have released a fix for this at `v2.3.2`, let me know if that works for you and I will close this out.

**Comment by DavidFH** [comment]
This worked, thank you for the update.

**Comment by sorensen** [comment]
Woo! Thanks for finding this.
