### ISSUE TITLE
Nested properties for object datatype

### ISSUE THREAD

**Issue by derekr** [majorleaguesoccer/respectify#7]
Hey! Thanks for the module. I'm really stoked on the introspection aspects it provides :D.

Have you considered supporting defining the available properties for an object type?

```js
server.post({
    path: '/users',
    version: '1.0.0',

    params: {
        url: 'string',
        profile: {
            dataTypes: ['object'],
            params: {
                email: 'string'
            }
        }
    }
}, controllers.post);
```

**Comment by sorensen** [comment]
Interesting, I have not considered this case. It shouldn't actually be too difficult. Personally I have yet to really use an object type parameter, as I consider the params to be the top level object, so I apologize for not having more in-depth object param support.

**Comment by sorensen** [comment]
Still working on this.

**Comment by sorensen** [comment]
@derekr Should be good to go on this.

Docs: https://github.com/majorleaguesoccer/respectify#objects

Example: 
  - Server: https://github.com/majorleaguesoccer/respectify/blob/master/example/server.js#L108-L134
  - Tests: https://github.com/majorleaguesoccer/respectify/blob/master/test.js#L647-L681
