### ISSUE TITLE
1.3.0 array validation breaks existing code

### ISSUE THREAD

**Issue by gcochard** [majorleaguesoccer/respectify#9]
Please don't introduce breaking changes without bumping the major revision. This should have been version `2.0.0`. I lost a week of debugging due to the change in array validation. You should revert the changes, release it as 1.3.2 or 1.4.2, and then re-publish as 2.0.0.

**Comment by sorensen** [comment]
Sorry about the troubles, it was not my intention to create breaking changes. Can you provide an example on how you are using the array data type that caused the issue?

**Comment by gcochard** [comment]
Here's a quick example:

```js
server.post({ path:'/test/:id',version:'1.0.0',description:'test',
  params: {
    id: { dataTypes: 'number', description: 'the test number', required: true},
    stuff: { dataTypes: ['array','string'], description: 'the stuff' }
  }
}, function(req,res,next){

}
```

I would like `stuff` to be either an array of objects or a string. With the previous version, the array would validate. With the current version, the array validation tries to find strings but finds objects instead.

I will definitely migrate to the new version (it is great that you do recursive validation), but it's a little jarring to *have* to do it due to npm's install behavior.

**Comment by sorensen** [comment]
Ah, I see, I've always interpreted a data type of `array` and `string` to mean either a string, or a list of strings.  One issue I see is that I've eliminated this type of behavior altogether, is this something you would like a parameter option for? 

Something like this on a route, or a global option:

```js
stuff: {
  dataTypes: ['array', 'string']
, recursive: false
}
```

**Comment by gcochard** [comment]
That would be a great option to add.

I think something like [mongoose's schema definition](http://mongoosejs.com/docs/schematypes.html) might be a little more flexible and declarative in the long run.

**Comment by sorensen** [comment]
@gcochard I have reverted the change in `1.3.2`, and added it back in `2.0.0`

**Comment by gcochard** [comment]
Thanks!

**Comment by sorensen** [comment]
No problem, I will try and get the recursive option in soon to preserve old functionality if desired.
